DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_STRATEGIES;
DROP TABLE IF EXISTS STRATEGIES;
DROP TABLE IF EXISTS SYMBOLS;

CREATE TABLE USER (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE STRATEGIES(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  api_ref TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE USER_STRATEGIES(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  strat_id INTEGER,
  symbol_id INTEGER,
  last_check TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  interim TEXT NOT NULL
);

CREATE TABLE SYMBOLS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  symbol TEXT NOT NULL,
  other_name TEXT
);

INSERT INTO SYMBOLS (symbol, other_name, full_symbol) VALUES ('SPY', 'S&P 500 Index', 'AMEX:SPY');
INSERT INTO SYMBOLS (symbol, other_name, full_symbol) VALUES ('SPX', 'S&P 500', 'TVC:SPX');
INSERT INTO SYMBOLS (symbol, other_name, full_symbol) VALUES ('DJI', 'Dow Jones Industrial Average', 'TVC:DJI');

INSERT INTO STRATEGIES (api_ref, name) VALUES ('to-do', 'STOCHASTIC');
INSERT INTO STRATEGIES (api_ref, name) VALUES ('to-do', 'BOLLINGER');
INSERT INTO STRATEGIES (api_ref, name) VALUES ('to-do', 'MACD');